name: Build and Release Lambda Layers

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Ensure build script is executable and run it
      run: |
        chmod +x ./build_layers.sh
        ./build_layers.sh manylinux2014_x86_64 manylinux2014_aarch64

    - name: List output ZIPs
      run: ls -lh built_lambda_layers/

    - name: Configure git user for commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch and checkout main branch for pushing built layers
      run: |
        git fetch origin main
        git checkout main

    - name: Commit built layers if changed and push to main branch
      run: |
        git add built_lambda_layers/
        if ! git diff --cached --quiet; then
          git commit -m "Build Lambda layers for ${{ github.ref_name }}"
          git push origin main
        else
          echo "No changes in built layers; skipping commit."
        fi

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
